import logging

LOGGING_FOLDER = r"C:/Projects/slo-dev/logs"
LOGGING_MAX_BYTES = 50 * 1024 * 1024
LOGGING_MAX_FILES = 10
LOGGIN_LEVEL = logging.DEBUG
SCRAPPER_STATES_FOLDER = r"C:/Projects/slo-dev/scrapper_states"

# MojeDelo
MOJE_DELO_NAME = "MojeDelo"
MOJE_DELO_BACKFILL = True
MOJE_DELO_FETCH_LIMIT = 10
MOJE_DELO_BACKFILL_LIMIT = 20
MOJE_DELO_RUN_INTERVAL_MINUTES = 60 * 6
MOJE_DELO_MAX_RUN_TIME_SECONDS = 60 * 30