BEGIN;

DROP TABLE IF EXISTS jobs CASCADE;

DROP TABLE IF EXISTS programming_languages CASCADE;
DROP TABLE IF EXISTS frameworks CASCADE;
DROP TABLE IF EXISTS databases CASCADE;
DROP TABLE IF EXISTS other_tools CASCADE;
DROP TABLE IF EXISTS job_specializations CASCADE;
DROP TABLE IF EXISTS industries CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
DROP TABLE IF EXISTS companies CASCADE;

DROP TYPE IF EXISTS seniority_level CASCADE;
DROP TYPE IF EXISTS employment_type CASCADE;
DROP TYPE IF EXISTS work_mode CASCADE;

COMMIT;
